[package]
name = "kv-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
sled = "0.34"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false 